In [1]:
import torch
import numpy as np

In [11]:
torch.tensor?

In [9]:
x = torch.tensor([1, 2, 3])
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [10]:
x = torch.tensor(np.array([1, 2, 3]))
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [15]:
x = torch.arange(12)
print(x.shape)
print(x.numel())
x

torch.Size([12])
12


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x = torch.arange(12, dtype = torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [19]:
X = x.reshape(3, 4)
print(X.shape)
print(X.numel())
X

torch.Size([3, 4])
12


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [33]:
torch.tensor([[0., 1., 2., 3.],
              [4., 5., 6., 7.],
              [8., 9., 10., 11.]])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
torch.randint(0, 10, size = (3, 3))

tensor([[3, 5, 0],
        [2, 0, 8],
        [3, 6, 1]])

In [26]:
torch.randn(3, 3)

tensor([[ 1.9109, -0.1849,  0.5269],
        [-0.0418, -0.3771, -1.5432],
        [ 0.1334, -1.3143,  0.5615]])

In [38]:
x = torch.arange(1, 5, dtype = torch.float64)
print(x)

print(torch.exp(x))
print(torch.sin(x))
print(torch.cos(x))
print(torch.log(x))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([ 2.7183,  7.3891, 20.0855, 54.5982], dtype=torch.float64)
tensor([ 0.8415,  0.9093,  0.1411, -0.7568], dtype=torch.float64)
tensor([ 0.5403, -0.4161, -0.9900, -0.6536], dtype=torch.float64)
tensor([0.0000, 0.6931, 1.0986, 1.3863], dtype=torch.float64)


In [44]:
print(torch.sum(x))
print(torch.mean(x))
print(torch.std(x))

tensor(10., dtype=torch.float64)
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)


In [50]:
print(X)
print(X.sum(dim = 0))
print(X.sum(dim = 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)
tensor([12., 15., 18., 21.], dtype=torch.float64)
tensor([ 6., 22., 38.], dtype=torch.float64)


In [51]:
# Lösung:

print(X[:, :2].sum(dim = 1))

tensor([ 1.,  9., 17.], dtype=torch.float64)


In [58]:
print(x)

print(x + 1)
print(x + torch.ones(4))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)


In [60]:
print(x)
print(x * 2)
print(x // 2)
print(x % 2)
print(x < 3)

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 4., 6., 8.], dtype=torch.float64)
tensor([0., 1., 1., 2.], dtype=torch.float64)
tensor([1., 0., 1., 0.], dtype=torch.float64)
tensor([ True,  True, False, False])


In [3]:
X = torch.ones(3, 3)
Y = torch.eye(3)

X == Y

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [4]:
v = torch.arange(3).reshape((3, 1))
w = torch.arange(2).reshape((1, 2))
print(v)
print(w)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [5]:
v + w

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [31]:
Z = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print(Z[0, 1])
print(Z[-1])
print(Z[:, -1])
print(Z[:, :2])

# Lösung:
print(Z[::2, 1])

tensor(2)
tensor([10, 11, 12])
tensor([ 3,  6,  9, 12])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])
tensor([2, 8])


In [32]:
print("id(Z):", id(Z))
Z = Z + torch.ones(4, 3)
print("id(Z):", id(Z)) # unter Umständen nicht wünschenswert!

id(Z): 140163074741232
id(Z): 140163074849312


In [33]:
print("id(Z):", id(Z))
Z[:] = Z + torch.ones(4, 3) # Wir bevorzugen im Allgemeinen "in place"-Operationen
print("id(Z):", id(Z))

id(Z): 140163074849312
id(Z): 140163074849312


In [34]:
print("id(Z):", id(Z))
Z[:] += torch.ones(4, 3) # Alternativ auch so
print("id(Z):", id(Z))

id(Z): 140163074849312
id(Z): 140163074849312


In [35]:
print("id(Z):", id(Z))
print("type(Z):", type(Z))
Z = Z.numpy()
print("id(Z):", id(Z))
print("type(Z):", type(Z))

id(Z): 140163074849312
type(Z): <class 'torch.Tensor'>
id(Z): 140163075356992
type(Z): <class 'numpy.ndarray'>


In [38]:
l = torch.tensor([1.0])

print(l)
print(l.numpy())
print(l.item())
print(int(l))
print(float(l))

tensor([1.])
[1.]
1.0
1
1.0
