In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
torch.tensor?

In [3]:
x = torch.tensor([1, 2, 3])
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [4]:
x = torch.tensor(np.array([1, 2, 3]))
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [5]:
x = torch.arange(12)
print(x.shape)
print(x.numel())
x

torch.Size([12])
12


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x = torch.arange(12, dtype = torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [7]:
X = x.reshape(3, 4)
print(X.shape)
print(X.numel())
X

torch.Size([3, 4])
12


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [8]:
torch.tensor([[0., 1., 2., 3.],
              [4., 5., 6., 7.],
              [8., 9., 10., 11.]])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
torch.randint(0, 10, size = (3, 3))

tensor([[8, 1, 3],
        [4, 4, 8],
        [8, 8, 9]])

In [13]:
torch.randn(3, 3)

tensor([[ 1.2728,  0.4583,  0.6823],
        [ 0.2954, -1.6962,  0.9978],
        [ 2.2792,  0.4649, -0.2758]])

In [14]:
x = torch.arange(1, 5, dtype = torch.float64)
print(x)

print(torch.exp(x))
print(torch.sin(x))
print(torch.cos(x))
print(torch.log(x))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([ 2.7183,  7.3891, 20.0855, 54.5982], dtype=torch.float64)
tensor([ 0.8415,  0.9093,  0.1411, -0.7568], dtype=torch.float64)
tensor([ 0.5403, -0.4161, -0.9900, -0.6536], dtype=torch.float64)
tensor([0.0000, 0.6931, 1.0986, 1.3863], dtype=torch.float64)


In [15]:
print(torch.sum(x))
print(torch.mean(x))
print(torch.std(x))

tensor(10., dtype=torch.float64)
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)


In [16]:
print(X)
print(X.sum(dim = 0))
print(X.sum(dim = 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)
tensor([12., 15., 18., 21.], dtype=torch.float64)
tensor([ 6., 22., 38.], dtype=torch.float64)


In [17]:
# Lösung:

print(X[:, :2].sum(dim = 1))

tensor([ 1.,  9., 17.], dtype=torch.float64)


In [18]:
print(x)

print(x + 1)
print(x + torch.ones(4))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)


In [19]:
print(x)
print(x * 2)
print(x // 2)
print(x % 2)
print(x < 3)

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 4., 6., 8.], dtype=torch.float64)
tensor([0., 1., 1., 2.], dtype=torch.float64)
tensor([1., 0., 1., 0.], dtype=torch.float64)
tensor([ True,  True, False, False])


In [20]:
X = torch.ones(3, 3)
Y = torch.eye(3)

X == Y

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [21]:
v = torch.arange(3).reshape((3, 1))
w = torch.arange(2).reshape((1, 2))
print(v)
print(w)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [22]:
v + w

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [23]:
Z = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print(Z[0, 1])
print(Z[-1])
print(Z[:, -1])
print(Z[:, :2])

# Lösung:
print(Z[::2, 1])

tensor(2)
tensor([10, 11, 12])
tensor([ 3,  6,  9, 12])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])
tensor([2, 8])


In [24]:
print("id(Z):", id(Z))
Z = Z + torch.ones(4, 3)
print("id(Z):", id(Z)) # unter Umständen nicht wünschenswert!

id(Z): 139703577467208
id(Z): 139703577401168


In [25]:
print("id(Z):", id(Z))
Z[:] = Z + torch.ones(4, 3) # Wir bevorzugen im Allgemeinen "in place"-Operationen
print("id(Z):", id(Z))

id(Z): 139703577401168
id(Z): 139703577401168


In [26]:
print("id(Z):", id(Z))
Z[:] += torch.ones(4, 3) # Alternativ auch so
print("id(Z):", id(Z))

id(Z): 139703577401168
id(Z): 139703577401168


In [27]:
print("id(Z):", id(Z))
print("type(Z):", type(Z))
Z = Z.numpy()
print("id(Z):", id(Z))
print("type(Z):", type(Z))

id(Z): 139703577401168
type(Z): <class 'torch.Tensor'>
id(Z): 139703577444960
type(Z): <class 'numpy.ndarray'>


In [28]:
l = torch.tensor([1.0])

print(l)
print(l.numpy())
print(l.item())
print(int(l))
print(float(l))

tensor([1.])
[1.]
1.0
1
1.0


In [29]:
from sklearn.datasets import load_boston

boston = load_boston()
print(boston["DESCR"])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [30]:
df = pd.DataFrame(boston["data"], columns = boston["feature_names"])
df["MEDV"] = boston["target"]

df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [31]:
input, output = df.iloc[:, :-1], df.iloc[:, -1]

In [32]:
input.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [33]:
output.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [35]:
X, y = torch.tensor(input.values), torch.tensor(output.values)

In [36]:
X[0]

tensor([6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
        6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
        4.9800e+00], dtype=torch.float64)

In [37]:
y[0]

tensor(24., dtype=torch.float64)

In [38]:
x = torch.tensor([1.0])
y = torch.tensor([2.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**y)
print(x % 2)
print(x // 2)

tensor([3.])
tensor([-1.])
tensor([2.])
tensor([0.5000])
tensor([1.])
tensor([1.])
tensor([0.])


In [39]:
v = torch.arange(5)
v

tensor([0, 1, 2, 3, 4])

In [40]:
print(v[1])
print(v.shape)
print(len(v))

tensor(1)
torch.Size([5])
5


In [41]:
M = torch.arange(12).reshape(4, 3)
M

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [42]:
M.T

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [43]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [44]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [51]:
T = torch.arange(27).reshape(3, 3, 3)
print(T, T.shape, len(T))

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]) torch.Size([3, 3, 3]) 3


In [57]:
U = torch.arange(24).reshape(2, 3, 4)
print(U, U.shape, len(U))

U = torch.arange(24).reshape(4, 3, 2)
print(U, U.shape, len(U))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) torch.Size([2, 3, 4]) 2
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]) torch.Size([4, 3, 2]) 4


In [48]:
print(A)

B = A.clone()

print(A+B)
print(A*B)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[ 2,  4,  6],
        [ 4,  0,  8],
        [ 6,  8, 10]])
tensor([[ 1,  4,  9],
        [ 4,  0, 16],
        [ 9, 16, 25]])


In [50]:
# Lösung:

print(T, T.shape)

U = T.clone()

print(T+U, (T+U).shape)
print(T*U, (T*U).shape)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]) torch.Size([3, 3, 3])
tensor([[[ 0,  2,  4],
         [ 6,  8, 10],
         [12, 14, 16]],

        [[18, 20, 22],
         [24, 26, 28],
         [30, 32, 34]],

        [[36, 38, 40],
         [42, 44, 46],
         [48, 50, 52]]]) torch.Size([3, 3, 3])
tensor([[[  0,   1,   4],
         [  9,  16,  25],
         [ 36,  49,  64]],

        [[ 81, 100, 121],
         [144, 169, 196],
         [225, 256, 289]],

        [[324, 361, 400],
         [441, 484, 529],
         [576, 625, 676]]]) torch.Size([3, 3, 3])


In [68]:
A = torch.arange(12).reshape(3, 4)
print(A)

print(A.sum(axis = 0, keepdims = True))
print(A.sum(axis = 1, keepdims = True))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[12, 15, 18, 21]])
tensor([[ 6],
        [22],
        [38]])


In [71]:
print(A.cumsum(axis = 0))
print(A.cumsum(axis = 1))

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21]])
tensor([[ 0,  1,  3,  6],
        [ 4,  9, 15, 22],
        [ 8, 17, 27, 38]])
