In [19]:
import torch
import numpy as np
import pandas as pd

In [11]:
torch.tensor?

In [9]:
x = torch.tensor([1, 2, 3])
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [10]:
x = torch.tensor(np.array([1, 2, 3]))
print(type(x))
x

<class 'torch.Tensor'>


tensor([1, 2, 3])

In [15]:
x = torch.arange(12)
print(x.shape)
print(x.numel())
x

torch.Size([12])
12


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x = torch.arange(12, dtype = torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       dtype=torch.float64)

In [19]:
X = x.reshape(3, 4)
print(X.shape)
print(X.numel())
X

torch.Size([3, 4])
12


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [33]:
torch.tensor([[0., 1., 2., 3.],
              [4., 5., 6., 7.],
              [8., 9., 10., 11.]])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
torch.randint(0, 10, size = (3, 3))

tensor([[3, 5, 0],
        [2, 0, 8],
        [3, 6, 1]])

In [26]:
torch.randn(3, 3)

tensor([[ 1.9109, -0.1849,  0.5269],
        [-0.0418, -0.3771, -1.5432],
        [ 0.1334, -1.3143,  0.5615]])

In [38]:
x = torch.arange(1, 5, dtype = torch.float64)
print(x)

print(torch.exp(x))
print(torch.sin(x))
print(torch.cos(x))
print(torch.log(x))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([ 2.7183,  7.3891, 20.0855, 54.5982], dtype=torch.float64)
tensor([ 0.8415,  0.9093,  0.1411, -0.7568], dtype=torch.float64)
tensor([ 0.5403, -0.4161, -0.9900, -0.6536], dtype=torch.float64)
tensor([0.0000, 0.6931, 1.0986, 1.3863], dtype=torch.float64)


In [44]:
print(torch.sum(x))
print(torch.mean(x))
print(torch.std(x))

tensor(10., dtype=torch.float64)
tensor(2.5000, dtype=torch.float64)
tensor(1.2910, dtype=torch.float64)


In [50]:
print(X)
print(X.sum(dim = 0))
print(X.sum(dim = 1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)
tensor([12., 15., 18., 21.], dtype=torch.float64)
tensor([ 6., 22., 38.], dtype=torch.float64)


In [51]:
# Lösung:

print(X[:, :2].sum(dim = 1))

tensor([ 1.,  9., 17.], dtype=torch.float64)


In [58]:
print(x)

print(x + 1)
print(x + torch.ones(4))

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)
tensor([2., 3., 4., 5.], dtype=torch.float64)


In [60]:
print(x)
print(x * 2)
print(x // 2)
print(x % 2)
print(x < 3)

tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([2., 4., 6., 8.], dtype=torch.float64)
tensor([0., 1., 1., 2.], dtype=torch.float64)
tensor([1., 0., 1., 0.], dtype=torch.float64)
tensor([ True,  True, False, False])


In [3]:
X = torch.ones(3, 3)
Y = torch.eye(3)

X == Y

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [4]:
v = torch.arange(3).reshape((3, 1))
w = torch.arange(2).reshape((1, 2))
print(v)
print(w)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])


In [5]:
v + w

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [31]:
Z = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])
print(Z[0, 1])
print(Z[-1])
print(Z[:, -1])
print(Z[:, :2])

# Lösung:
print(Z[::2, 1])

tensor(2)
tensor([10, 11, 12])
tensor([ 3,  6,  9, 12])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])
tensor([2, 8])


In [32]:
print("id(Z):", id(Z))
Z = Z + torch.ones(4, 3)
print("id(Z):", id(Z)) # unter Umständen nicht wünschenswert!

id(Z): 140163074741232
id(Z): 140163074849312


In [33]:
print("id(Z):", id(Z))
Z[:] = Z + torch.ones(4, 3) # Wir bevorzugen im Allgemeinen "in place"-Operationen
print("id(Z):", id(Z))

id(Z): 140163074849312
id(Z): 140163074849312


In [34]:
print("id(Z):", id(Z))
Z[:] += torch.ones(4, 3) # Alternativ auch so
print("id(Z):", id(Z))

id(Z): 140163074849312
id(Z): 140163074849312


In [35]:
print("id(Z):", id(Z))
print("type(Z):", type(Z))
Z = Z.numpy()
print("id(Z):", id(Z))
print("type(Z):", type(Z))

id(Z): 140163074849312
type(Z): <class 'torch.Tensor'>
id(Z): 140163075356992
type(Z): <class 'numpy.ndarray'>


In [38]:
l = torch.tensor([1.0])

print(l)
print(l.numpy())
print(l.item())
print(int(l))
print(float(l))

tensor([1.])
[1.]
1.0
1
1.0


In [20]:
from sklearn.datasets import load_boston

boston = load_boston()
print(boston["DESCR"])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [21]:
df = pd.DataFrame(boston["data"], columns = boston["feature_names"])
df["MEDV"] = boston["target"]

df.head()

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [30]:
input, output = df.iloc[:, :-1], df.iloc[:, -1]

In [31]:
input.head()

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [32]:
output.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: MEDV, dtype: float64

In [33]:
X, y = torch.tensor(inputs.values), torch.tensor(output.values)

In [37]:
X[0]

tensor([6.3200e-03, 1.8000e+01, 2.3100e+00, 0.0000e+00, 5.3800e-01, 6.5750e+00,
        6.5200e+01, 4.0900e+00, 1.0000e+00, 2.9600e+02, 1.5300e+01, 3.9690e+02,
        4.9800e+00], dtype=torch.float64)

In [36]:
y[0]

tensor(24., dtype=torch.float64)

In [39]:
x = torch.tensor([1.0])
y = torch.tensor([2.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x**y)
print(x % 2)
print(x // 2)

tensor([3.])
tensor([-1.])
tensor([2.])
tensor([0.5000])
tensor([1.])
tensor([1.])
tensor([0.])


In [41]:
v = torch.arange(5)
v

tensor([0, 1, 2, 3, 4])

In [43]:
print(v[1])
print(v.shape)
print(len(v))

tensor(1)
torch.Size([5])
5


In [45]:
M = torch.arange(12).reshape(4, 3)
M

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [46]:
M.T

tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]])

In [47]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [48]:
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [50]:
T = torch.arange(27).reshape(3, 3, 3)
T

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])